#
# This config-file is only needed for development. Instead of changing the url
# everytime you work locally on the project, you start both config-files, overwriting
# the first one with the development variables needed.
#
# Start development with › $ jekyll serve --config _config.yml,_config_dev.yml


url: 'http://localhost:4000'
baseurl: ''
#sass:
  # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
#  sass_dir: _sass
#  style: :expanded
#  line_numbers: true
